name: caiman
channels:
- conda-forge
dependencies:
- python >=3.10
- av
- bokeh >=3.1.1
- coverage
- cython
- h5py
- holoviews >=1.16.2
- ipykernel
- ipython
- ipyparallel
- jupyter
- jupyter_bokeh
- matplotlib
- moviepy
- mypy
- nose
- numpy <2.0.0
- numpydoc
- opencv
- panel >=1.0.2
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- tifffile
- tk
- tqdm
- yapf
- z5py >= 2.0.15
- keras
- shapely
- cvxpy
- natsort
- seaborn
- ffmpeg-python
- python-igraph
- jupyterlab
- jupyterlab-git
- nd2reader
- chart-studio
- plotly
- pytables
- openpyxl
- jupyterlab_code_formatter
- black
- isort
- pynrrd
- lmfit
- numba
- llvmlite
- autograd 
- oasis-deconv
- nibabel
- webcolors
- scikit-spatial
- emcee
- dtw-python
- dtaidistance
- pip

- pip:
  - antspyx
  - nd2
  - tensorflow-cpu
