name: caiman
channels:
- conda-forge
dependencies:
- pip
- caiman>=1.11
- shapely
- cvxpy
- natsort
- seaborn
- ffmpeg-python
- python-igraph
- jupyterlab
- nd2reader
- chart-studio
- plotly
- pytables
- openpyxl
- black
- isort
- pynrrd
- numba
- llvmlite
- autograd
- oasis-deconv
- nibabel
- webcolors
- tabulate
- scikit-spatial
- aicsimageio
- pip:
  - antspyx
  - nd2
  - aicspylibczi>=3.1.1
  - fsspec>=2022.8.0
  - git+https://github.com/ahwillia/netrep.git
