name: jaxenv
channels:
- conda-forge
dependencies:
- numpy
- scipy
- ipython
- jupyterlab
- ipywidgets
- seaborn
- pip
- pip:
  - jax[cuda11_pip]==0.4.7+cuda11.cudnn82 # last version with cuda11.cudnn82 support
  - numpyro
  - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
