name: jax_gpu
channels:
- conda-forge
dependencies:
- python
- numpy<2
- ipython
- jupyterlab
- ipywidgets
- seaborn
- tqdm
- scikit-learn
- h5py
- nd2reader
- optax
- blackjax
- pip
- pip:
  - graphviz
  - jax[cuda12]
  - numpyro
