name: jaxenv
channels:
- conda-forge
dependencies:
- python
- numpy<2
- ipython
- jupyterlab
- ipywidgets
- seaborn
- tqdm
- scikit-learn
- h5py
- optax
- blackjax
- nd2reader
- pip
- pip:
  - graphviz
  # - jax[cpu]
  - numpyro[cpu]
